# Generated by Django 3.0.3 on 2020-03-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore_scotland_app', '0003_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='picture',
        ),
    ]
