# Generated by Django 3.0.3 on 2020-03-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_scotland_app', '0004_auto_20200316_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='categories',
            field=models.CharField(choices=[('LS', 'Landscape'), ('AC', 'Architecture'), ('PP', 'People')], default='LS', max_length=2),
        ),
    ]
