# Generated by Django 3.0.3 on 2020-03-17 14:30

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('explore_scotland_app', '0009_auto_20200316_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='photo',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '1024x1024', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '30x30', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=image_cropping.fields.ImageCropField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=image_cropping.fields.ImageCropField(upload_to=''),
        ),
    ]
