# Generated by Django 3.0.3 on 2020-03-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore_scotland_app', '0009_auto_20200316_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-date_added',)},
        ),
    ]
