# Generated by Django 3.0.3 on 2020-03-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore_scotland_app', '0010_auto_20200317_1430'),
        ('explore_scotland_app', '0010_auto_20200317_2325'),
    ]

    operations = [
    ]
