# Generated by Django 3.0.3 on 2020-03-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_scotland_app', '0011_merge_20200317_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
