# Generated by Django 3.0.3 on 2020-03-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_scotland_app', '0012_auto_20200317_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
