# Generated by Django 3.0.3 on 2020-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_scotland_app', '0013_auto_20200318_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='picture_square',
            field=models.ImageField(default='c', upload_to=''),
            preserve_default=False,
        ),
    ]
