# Generated by Django 3.0.3 on 2020-03-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore_scotland_app', '0014_photo_picture_square'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='picture_square',
        ),
    ]
